// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Attachment struct {
	ID           uuid.UUID
	Label        string
	Type         string
	ContentPath  string
	RequiredVars []string
	IsPublic     bool
	UploadedAt   pgtype.Timestamptz
}
