// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const count = `-- name: Count :one
SELECT COUNT(*) FROM attachments
WHERE
    ($1::uuid IS NULL OR id = $1)
    AND
    ($2::text IS NULL OR LOWER(label) ILIKE '%' || LOWER($2) || '%')
    AND
    ($3::text IS NULL OR type = $3)
`

type CountParams struct {
	ID    *uuid.UUID
	Label pgtype.Text
	Type  pgtype.Text
}

func (q *Queries) Count(ctx context.Context, arg CountParams) (int64, error) {
	row := q.db.QueryRow(ctx, count, arg.ID, arg.Label, arg.Type)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const delete = `-- name: Delete :exec
DELETE FROM attachments
WHERE id = $1
`

func (q *Queries) Delete(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, delete, id)
	return err
}

const query = `-- name: Query :many
SELECT id, label, type, content_path, required_vars, is_public, uploaded_at FROM attachments
WHERE
    ($1::uuid IS NULL OR id = $1)
    AND
    ($2::text IS NULL OR LOWER(label) ILIKE '%' || LOWER($2) || '%')
    AND
    ($3::text IS NULL OR type = $3)
ORDER BY
    CASE WHEN $4::text = 'a_asc' THEN id::text END ASC,
    CASE WHEN $4::text = 'a_desc' THEN id::text END DESC,
    CASE WHEN $4::text = 'b_asc' THEN label END ASC,
    CASE WHEN $4::text = 'b_desc' THEN label END DESC,
    CASE WHEN $4::text = 'c_asc' THEN type END ASC,
    CASE WHEN $4::text = 'c_desc' THEN type END DESC,
    CASE WHEN $4::text = 'd_asc' THEN uploaded_at END ASC,
    CASE WHEN $4::text = 'd_desc' THEN uploaded_at END DESC,
    id DESC
LIMIT $6 OFFSET $5
`

type QueryParams struct {
	ID        *uuid.UUID
	Label     pgtype.Text
	Type      pgtype.Text
	OrderBy   string
	OffsetVal int32
	LimitVal  int32
}

func (q *Queries) Query(ctx context.Context, arg QueryParams) ([]Attachment, error) {
	rows, err := q.db.Query(ctx, query,
		arg.ID,
		arg.Label,
		arg.Type,
		arg.OrderBy,
		arg.OffsetVal,
		arg.LimitVal,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Attachment
	for rows.Next() {
		var i Attachment
		if err := rows.Scan(
			&i.ID,
			&i.Label,
			&i.Type,
			&i.ContentPath,
			&i.RequiredVars,
			&i.IsPublic,
			&i.UploadedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const queryByID = `-- name: QueryByID :one
SELECT id, label, type, content_path, required_vars, is_public, uploaded_at FROM attachments
WHERE id = $1
`

func (q *Queries) QueryByID(ctx context.Context, id uuid.UUID) (Attachment, error) {
	row := q.db.QueryRow(ctx, queryByID, id)
	var i Attachment
	err := row.Scan(
		&i.ID,
		&i.Label,
		&i.Type,
		&i.ContentPath,
		&i.RequiredVars,
		&i.IsPublic,
		&i.UploadedAt,
	)
	return i, err
}

const save = `-- name: Save :exec
INSERT INTO attachments (
    id,
    label,
    type,
    content_path,
    required_vars,
    is_public,
    uploaded_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
`

type SaveParams struct {
	ID           uuid.UUID
	Label        string
	Type         string
	ContentPath  string
	RequiredVars []string
	IsPublic     bool
	UploadedAt   pgtype.Timestamptz
}

func (q *Queries) Save(ctx context.Context, arg SaveParams) error {
	_, err := q.db.Exec(ctx, save,
		arg.ID,
		arg.Label,
		arg.Type,
		arg.ContentPath,
		arg.RequiredVars,
		arg.IsPublic,
		arg.UploadedAt,
	)
	return err
}

const update = `-- name: Update :exec
UPDATE attachments
SET
    label = $1,
    type = $2,
    content_path = $3,
    required_vars = $4,
    is_public = $5,
    uploaded_at = $6
WHERE id = $7
`

type UpdateParams struct {
	Label        string
	Type         string
	ContentPath  string
	RequiredVars []string
	IsPublic     bool
	UploadedAt   pgtype.Timestamptz
	ID           uuid.UUID
}

func (q *Queries) Update(ctx context.Context, arg UpdateParams) error {
	_, err := q.db.Exec(ctx, update,
		arg.Label,
		arg.Type,
		arg.ContentPath,
		arg.RequiredVars,
		arg.IsPublic,
		arg.UploadedAt,
		arg.ID,
	)
	return err
}
