// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"net/netip"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Campaign struct {
	ID     uuid.UUID
	Status string
}

type Employee struct {
	ID           uuid.UUID
	DepartmentID *uuid.UUID
	FirstName    string
	LastName     string
	Email        string
	PhoneNumber  pgtype.Text
	Attributes   []byte
}

type Event struct {
	ID         uuid.UUID
	CampaignID uuid.UUID
	EmployeeID uuid.UUID
	Type       string
	OccurredAt pgtype.Timestamp
	IpAddress  *netip.Addr
	UserAgent  pgtype.Text
	Referer    pgtype.Text
}

type Target struct {
	ID          uuid.UUID
	Token       string
	EmployeeID  uuid.UUID
	CampaignID  uuid.UUID
	Status      string
	ScheduledAt pgtype.Timestamptz
	CreatedAt   pgtype.Timestamptz
}
