// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package sqlc

import (
	"context"
	"net/netip"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const count = `-- name: Count :one
SELECT COUNT(*) FROM targets t
JOIN employees e ON e.id = t.employee_id
WHERE
    ($1::uuid IS NULL OR t.id = $1)
    AND
    ($2::uuid IS NULL OR t.campaign_id = $2)
    AND
    ($3::uuid IS NULL OR t.employee_id = $3)
    AND
    ($4::text IS NULL OR t.status = $4)
    AND
    ($5::text IS NULL OR LOWER(e.first_name || ' ' || e.last_name) ILIKE '%' || LOWER($5) || '%')
`

type CountParams struct {
	ID         *uuid.UUID
	CampaignID *uuid.UUID
	EmployeeID *uuid.UUID
	Status     pgtype.Text
	FullName   pgtype.Text
}

func (q *Queries) Count(ctx context.Context, arg CountParams) (int64, error) {
	row := q.db.QueryRow(ctx, count,
		arg.ID,
		arg.CampaignID,
		arg.EmployeeID,
		arg.Status,
		arg.FullName,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const query = `-- name: Query :many
WITH matched_targets AS (
    SELECT
        t.id,
        t.token,
        t.campaign_id,
        t.employee_id,
        e.first_name,
        e.last_name,
        t.status,
        t.scheduled_at,
        t.created_at
    FROM targets t
    JOIN employees e ON e.id = t.employee_id
    WHERE
        ($2::uuid IS NULL OR t.id = $2)
        AND
        ($3::uuid IS NULL OR t.campaign_id = $3)
        AND
        ($4::uuid IS NULL OR t.employee_id = $4)
        AND
        ($5::text IS NULL OR t.status = $5)
        AND
        ($6::text IS NULL OR LOWER(e.first_name || ' ' || e.last_name) ILIKE '%' || LOWER($6) || '%')
    ORDER BY
        CASE WHEN $1::text = 'a_asc' THEN t.id::text END ASC,
        CASE WHEN $1::text = 'a_desc' THEN t.id::text END DESC,
        CASE WHEN $1::text = 'b_asc' THEN e.first_name END ASC,
        CASE WHEN $1::text = 'b_desc' THEN e.first_name END DESC,
        CASE WHEN $1::text = 'c_asc' THEN e.last_name END ASC,
        CASE WHEN $1::text = 'c_desc' THEN e.last_name END DESC,
        CASE WHEN $1::text = 'd_asc' THEN t.status END ASC,
        CASE WHEN $1::text = 'd_desc' THEN t.status END DESC,
        t.id DESC
    LIMIT $8 OFFSET $7
)
SELECT
    mt.id,
    mt.token,
    mt.campaign_id,
    mt.employee_id,
    mt.first_name,
    mt.last_name,
    mt.status,
    mt.scheduled_at,
    mt.created_at,
    ev.type AS event_type,
    ev.ip_address AS event_ip_address,
    ev.user_agent AS event_user_agent,
    ev.referer AS event_referer,
    ev.occurred_at AS event_occurred_at
FROM matched_targets mt
LEFT JOIN events ev
    ON ev.campaign_id = mt.campaign_id
    AND ev.employee_id = mt.employee_id
ORDER BY
    CASE WHEN $1::text = 'a_asc' THEN mt.id::text END ASC,
    CASE WHEN $1::text = 'a_desc' THEN mt.id::text END DESC,
    CASE WHEN $1::text = 'b_asc' THEN mt.first_name END ASC,
    CASE WHEN $1::text = 'b_desc' THEN mt.first_name END DESC,
    CASE WHEN $1::text = 'c_asc' THEN mt.last_name END ASC,
    CASE WHEN $1::text = 'c_desc' THEN mt.last_name END DESC,
    CASE WHEN $1::text = 'd_asc' THEN mt.status END ASC,
    CASE WHEN $1::text = 'd_desc' THEN mt.status END DESC,
    mt.id DESC,
    ev.occurred_at DESC,
    ev.id DESC
`

type QueryParams struct {
	OrderBy    string
	ID         *uuid.UUID
	CampaignID *uuid.UUID
	EmployeeID *uuid.UUID
	Status     pgtype.Text
	FullName   pgtype.Text
	OffsetVal  int32
	LimitVal   int32
}

type QueryRow struct {
	ID              uuid.UUID
	Token           string
	CampaignID      uuid.UUID
	EmployeeID      uuid.UUID
	FirstName       string
	LastName        string
	Status          string
	ScheduledAt     pgtype.Timestamptz
	CreatedAt       pgtype.Timestamptz
	EventType       pgtype.Text
	EventIpAddress  *netip.Addr
	EventUserAgent  pgtype.Text
	EventReferer    pgtype.Text
	EventOccurredAt pgtype.Timestamp
}

func (q *Queries) Query(ctx context.Context, arg QueryParams) ([]QueryRow, error) {
	rows, err := q.db.Query(ctx, query,
		arg.OrderBy,
		arg.ID,
		arg.CampaignID,
		arg.EmployeeID,
		arg.Status,
		arg.FullName,
		arg.OffsetVal,
		arg.LimitVal,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []QueryRow
	for rows.Next() {
		var i QueryRow
		if err := rows.Scan(
			&i.ID,
			&i.Token,
			&i.CampaignID,
			&i.EmployeeID,
			&i.FirstName,
			&i.LastName,
			&i.Status,
			&i.ScheduledAt,
			&i.CreatedAt,
			&i.EventType,
			&i.EventIpAddress,
			&i.EventUserAgent,
			&i.EventReferer,
			&i.EventOccurredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
