// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"
)

type Querier interface {
	Count(ctx context.Context, arg CountParams) (int64, error)
	Query(ctx context.Context, arg QueryParams) ([]QueryRow, error)
}

var _ Querier = (*Queries)(nil)
