// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const queryByID = `-- name: QueryByID :one
SELECT id, name, logo_url, attributes FROM organizations WHERE id = $1
`

func (q *Queries) QueryByID(ctx context.Context, id uuid.UUID) (Organization, error) {
	row := q.db.QueryRow(ctx, queryByID, id)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.LogoUrl,
		&i.Attributes,
	)
	return i, err
}

const save = `-- name: Save :exec
INSERT INTO organizations (id, name, attributes)
VALUES ($1, $2, $3)
ON CONFLICT (id) DO UPDATE
SET name = EXCLUDED.name, attributes = EXCLUDED.attributes
`

type SaveParams struct {
	ID         uuid.UUID
	Name       string
	Attributes []byte
}

func (q *Queries) Save(ctx context.Context, arg SaveParams) error {
	_, err := q.db.Exec(ctx, save, arg.ID, arg.Name, arg.Attributes)
	return err
}

const updateLogo = `-- name: UpdateLogo :exec
UPDATE organizations
SET logo_url = $1
WHERE id = $2
`

type UpdateLogoParams struct {
	LogoUrl pgtype.Text
	ID      uuid.UUID
}

func (q *Queries) UpdateLogo(ctx context.Context, arg UpdateLogoParams) error {
	_, err := q.db.Exec(ctx, updateLogo, arg.LogoUrl, arg.ID)
	return err
}
