// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const queryByID = `-- name: QueryByID :one
SELECT id, label, attachment_id, attributes FROM organizations WHERE id = $1
`

func (q *Queries) QueryByID(ctx context.Context, id uuid.UUID) (Organization, error) {
	row := q.db.QueryRow(ctx, queryByID, id)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Label,
		&i.AttachmentID,
		&i.Attributes,
	)
	return i, err
}

const save = `-- name: Save :exec
INSERT INTO organizations (id, label, attachment_id, attributes)
VALUES ($1, $2, $3, $4)
`

type SaveParams struct {
	ID           uuid.UUID
	Label        string
	AttachmentID *uuid.UUID
	Attributes   []byte
}

func (q *Queries) Save(ctx context.Context, arg SaveParams) error {
	_, err := q.db.Exec(ctx, save,
		arg.ID,
		arg.Label,
		arg.AttachmentID,
		arg.Attributes,
	)
	return err
}

const update = `-- name: Update :exec
UPDATE organizations
SET label = $1, attachment_id = $2, attributes = $3
WHERE id = $4
`

type UpdateParams struct {
	Label        string
	AttachmentID *uuid.UUID
	Attributes   []byte
	ID           uuid.UUID
}

func (q *Queries) Update(ctx context.Context, arg UpdateParams) error {
	_, err := q.db.Exec(ctx, update,
		arg.Label,
		arg.AttachmentID,
		arg.Attributes,
		arg.ID,
	)
	return err
}
