// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	GetByID(ctx context.Context, id uuid.UUID) (Organization, error)
	Save(ctx context.Context, arg SaveParams) error
}

var _ Querier = (*Queries)(nil)
