// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Campaign struct {
	ID         uuid.UUID
	MessageID  *uuid.UUID
	LandingID  *uuid.UUID
	Label      string
	Domain     string
	Status     string
	DateFrom   pgtype.Timestamptz
	DateTo     pgtype.Timestamptz
	Attributes []byte
}
