// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const count = `-- name: Count :one
SELECT COUNT(*) FROM campaigns
WHERE
    ($1::uuid IS NULL OR id = $1) AND
    ($2::text IS NULL OR type = $2) AND
    ($3::text IS NULL OR LOWER(label) ILIKE '%' || LOWER($3) || '%') AND
    ($4::text IS NULL OR status = $4) AND
    ($5::timestamptz IS NULL OR date_to > $5) AND
    ($6::timestamptz IS NULL OR date_from < $6)
`

type CountParams struct {
	ID       *uuid.UUID
	Type     pgtype.Text
	Label    pgtype.Text
	Status   pgtype.Text
	DateFrom pgtype.Timestamptz
	DateTo   pgtype.Timestamptz
}

func (q *Queries) Count(ctx context.Context, arg CountParams) (int64, error) {
	row := q.db.QueryRow(ctx, count,
		arg.ID,
		arg.Type,
		arg.Label,
		arg.Status,
		arg.DateFrom,
		arg.DateTo,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const delete = `-- name: Delete :exec
DELETE FROM campaigns
WHERE id = $1
`

func (q *Queries) Delete(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, delete, id)
	return err
}

const query = `-- name: Query :many
SELECT id, type, message_id, landing_id, education_id, max_education_text_id, label, domain, status, date_from, date_to, attributes FROM campaigns
WHERE
    ($1::uuid IS NULL OR id = $1)
    AND
    ($2::text IS NULL OR type = $2)
    AND
    ($3::text IS NULL OR LOWER(label) ILIKE '%' || LOWER($3) || '%')
    AND
    ($4::text IS NULL OR status = $4)
    AND
    ($5::timestamptz IS NULL OR date_to > $5)
    AND
    ($6::timestamptz IS NULL OR date_from < $6)
ORDER BY
    CASE WHEN $7::text = 'a_asc' THEN id::text END ASC,
    CASE WHEN $7::text = 'a_desc' THEN id::text END DESC,
    CASE WHEN $7::text = 'b_asc' THEN label END ASC,
    CASE WHEN $7::text = 'b_desc' THEN label END DESC,
    CASE WHEN $7::text = 'c_asc' THEN status END ASC,
    CASE WHEN $7::text = 'c_desc' THEN status END DESC,
    CASE WHEN $7::text = 'd_asc' THEN date_from END ASC,
    CASE WHEN $7::text = 'd_desc' THEN date_from END DESC,
    CASE WHEN $7::text = 'e_asc' THEN date_to END ASC,
    CASE WHEN $7::text = 'e_desc' THEN date_to END DESC,
    id DESC
LIMIT $9 OFFSET $8
`

type QueryParams struct {
	ID        *uuid.UUID
	Type      pgtype.Text
	Label     pgtype.Text
	Status    pgtype.Text
	DateFrom  pgtype.Timestamptz
	DateTo    pgtype.Timestamptz
	OrderBy   string
	OffsetVal int32
	LimitVal  int32
}

func (q *Queries) Query(ctx context.Context, arg QueryParams) ([]Campaign, error) {
	rows, err := q.db.Query(ctx, query,
		arg.ID,
		arg.Type,
		arg.Label,
		arg.Status,
		arg.DateFrom,
		arg.DateTo,
		arg.OrderBy,
		arg.OffsetVal,
		arg.LimitVal,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Campaign
	for rows.Next() {
		var i Campaign
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.MessageID,
			&i.LandingID,
			&i.EducationID,
			&i.MaxEducationTextID,
			&i.Label,
			&i.Domain,
			&i.Status,
			&i.DateFrom,
			&i.DateTo,
			&i.Attributes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const queryByID = `-- name: QueryByID :one
SELECT id, type, message_id, landing_id, education_id, max_education_text_id, label, domain, status, date_from, date_to, attributes FROM campaigns
WHERE id = $1
`

func (q *Queries) QueryByID(ctx context.Context, id uuid.UUID) (Campaign, error) {
	row := q.db.QueryRow(ctx, queryByID, id)
	var i Campaign
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.MessageID,
		&i.LandingID,
		&i.EducationID,
		&i.MaxEducationTextID,
		&i.Label,
		&i.Domain,
		&i.Status,
		&i.DateFrom,
		&i.DateTo,
		&i.Attributes,
	)
	return i, err
}

const queryExpired = `-- name: QueryExpired :many
SELECT id, type, message_id, landing_id, education_id, max_education_text_id, label, domain, status, date_from, date_to, attributes FROM campaigns
WHERE
    status = 'ACTIVE'
    AND date_to IS NOT NULL
    AND date_to <= NOW()
ORDER BY date_to ASC, id ASC
`

func (q *Queries) QueryExpired(ctx context.Context) ([]Campaign, error) {
	rows, err := q.db.Query(ctx, queryExpired)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Campaign
	for rows.Next() {
		var i Campaign
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.MessageID,
			&i.LandingID,
			&i.EducationID,
			&i.MaxEducationTextID,
			&i.Label,
			&i.Domain,
			&i.Status,
			&i.DateFrom,
			&i.DateTo,
			&i.Attributes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const save = `-- name: Save :exec
INSERT INTO campaigns (
    id,
    type,
    message_id,
    landing_id,
    education_id,
    max_education_text_id,
    label,
    domain,
    status,
    date_from,
    date_to,
    attributes
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12
)
`

type SaveParams struct {
	ID                 uuid.UUID
	Type               string
	MessageID          *uuid.UUID
	LandingID          *uuid.UUID
	EducationID        *uuid.UUID
	MaxEducationTextID *uuid.UUID
	Label              string
	Domain             string
	Status             string
	DateFrom           pgtype.Timestamptz
	DateTo             pgtype.Timestamptz
	Attributes         []byte
}

func (q *Queries) Save(ctx context.Context, arg SaveParams) error {
	_, err := q.db.Exec(ctx, save,
		arg.ID,
		arg.Type,
		arg.MessageID,
		arg.LandingID,
		arg.EducationID,
		arg.MaxEducationTextID,
		arg.Label,
		arg.Domain,
		arg.Status,
		arg.DateFrom,
		arg.DateTo,
		arg.Attributes,
	)
	return err
}

const update = `-- name: Update :exec
UPDATE campaigns
SET
    type = $1,
    message_id = $2,
    landing_id = $3,
    education_id = $4,
    max_education_text_id = $5,
    label = $6,
    domain = $7,
    status = $8,
    date_from = $9,
    date_to = $10,
    attributes = $11
WHERE id = $12
`

type UpdateParams struct {
	Type               string
	MessageID          *uuid.UUID
	LandingID          *uuid.UUID
	EducationID        *uuid.UUID
	MaxEducationTextID *uuid.UUID
	Label              string
	Domain             string
	Status             string
	DateFrom           pgtype.Timestamptz
	DateTo             pgtype.Timestamptz
	Attributes         []byte
	ID                 uuid.UUID
}

func (q *Queries) Update(ctx context.Context, arg UpdateParams) error {
	_, err := q.db.Exec(ctx, update,
		arg.Type,
		arg.MessageID,
		arg.LandingID,
		arg.EducationID,
		arg.MaxEducationTextID,
		arg.Label,
		arg.Domain,
		arg.Status,
		arg.DateFrom,
		arg.DateTo,
		arg.Attributes,
		arg.ID,
	)
	return err
}
