// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Employee struct {
	ID           uuid.UUID
	DepartmentID *uuid.UUID
	FirstName    string
	LastName     string
	Email        string
	PhoneNumber  pgtype.Text
	Attributes   []byte
}
