// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const count = `-- name: Count :one
SELECT COUNT(*) FROM employees
WHERE 
    ($1::uuid IS NULL OR id = $1) AND
    ($2::uuid IS NULL OR department_id = $2) AND
    ($3::text IS NULL OR LOWER(first_name || ' ' || last_name) ILIKE '%' || LOWER($3) || '%') AND
    ($4::text IS NULL OR LOWER(email) ILIKE '%' || LOWER($4) || '%') AND
    ($5::text IS NULL OR phone_number ILIKE '%' || $5 || '%')
`

type CountParams struct {
	ID           *uuid.UUID
	DepartmentID *uuid.UUID
	FullName     pgtype.Text
	Email        pgtype.Text
	PhoneNumber  pgtype.Text
}

func (q *Queries) Count(ctx context.Context, arg CountParams) (int64, error) {
	row := q.db.QueryRow(ctx, count,
		arg.ID,
		arg.DepartmentID,
		arg.FullName,
		arg.Email,
		arg.PhoneNumber,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const delete = `-- name: Delete :exec
DELETE FROM employees
WHERE id = $1
`

func (q *Queries) Delete(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, delete, id)
	return err
}

const query = `-- name: Query :many
SELECT id, department_id, first_name, last_name, email, phone_number, attributes FROM employees
WHERE 
    -- Точный поиск по ID (если передан)
    ($1::uuid IS NULL OR id = $1) 
    AND
    -- Поиск по отделу
    ($2::uuid IS NULL OR department_id = $2)
    AND
    -- Умный поиск по имени и фамилии одной строкой (MVP вариант)
    ($3::text IS NULL OR LOWER(first_name || ' ' || last_name) ILIKE '%' || LOWER($3) || '%')
    AND
    -- Поиск по email
    ($4::text IS NULL OR LOWER(email) ILIKE '%' || LOWER($4) || '%')
    AND
    -- Поиск по телефону
    ($5::text IS NULL OR phone_number ILIKE '%' || $5 || '%')
ORDER BY 
    -- Сортировка напрямую по бизнес-константам (a=ID, b=FirstName, c=LastName, d=Email, e=Phone)
    CASE WHEN $6::text = 'a_asc' THEN id::text END ASC,
    CASE WHEN $6::text = 'a_desc' THEN id::text END DESC,
    CASE WHEN $6::text = 'b_asc' THEN first_name END ASC,
    CASE WHEN $6::text = 'b_desc' THEN first_name END DESC,
    CASE WHEN $6::text = 'c_asc' THEN last_name END ASC,
    CASE WHEN $6::text = 'c_desc' THEN last_name END DESC,
    CASE WHEN $6::text = 'd_asc' THEN email END ASC,
    CASE WHEN $6::text = 'd_desc' THEN email END DESC,
    CASE WHEN $6::text = 'e_asc' THEN phone_number END ASC,
    CASE WHEN $6::text = 'e_desc' THEN phone_number END DESC
LIMIT $8 OFFSET $7
`

type QueryParams struct {
	ID           *uuid.UUID
	DepartmentID *uuid.UUID
	FullName     pgtype.Text
	Email        pgtype.Text
	PhoneNumber  pgtype.Text
	OrderBy      string
	OffsetVal    int32
	LimitVal     int32
}

func (q *Queries) Query(ctx context.Context, arg QueryParams) ([]Employee, error) {
	rows, err := q.db.Query(ctx, query,
		arg.ID,
		arg.DepartmentID,
		arg.FullName,
		arg.Email,
		arg.PhoneNumber,
		arg.OrderBy,
		arg.OffsetVal,
		arg.LimitVal,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Employee
	for rows.Next() {
		var i Employee
		if err := rows.Scan(
			&i.ID,
			&i.DepartmentID,
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.PhoneNumber,
			&i.Attributes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const queryByID = `-- name: QueryByID :one
SELECT id, department_id, first_name, last_name, email, phone_number, attributes FROM employees
WHERE id = $1
`

func (q *Queries) QueryByID(ctx context.Context, id uuid.UUID) (Employee, error) {
	row := q.db.QueryRow(ctx, queryByID, id)
	var i Employee
	err := row.Scan(
		&i.ID,
		&i.DepartmentID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.PhoneNumber,
		&i.Attributes,
	)
	return i, err
}

const save = `-- name: Save :exec
INSERT INTO employees (
    id, 
    department_id, 
    first_name, 
    last_name, 
    email, 
    phone_number, 
    attributes
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
`

type SaveParams struct {
	ID           uuid.UUID
	DepartmentID *uuid.UUID
	FirstName    string
	LastName     string
	Email        string
	PhoneNumber  pgtype.Text
	Attributes   []byte
}

func (q *Queries) Save(ctx context.Context, arg SaveParams) error {
	_, err := q.db.Exec(ctx, save,
		arg.ID,
		arg.DepartmentID,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.PhoneNumber,
		arg.Attributes,
	)
	return err
}

const update = `-- name: Update :exec
UPDATE employees
SET 
    department_id = $1, 
    first_name = $2, 
    last_name = $3, 
    email = $4, 
    phone_number = $5, 
    attributes = $6
WHERE id = $7
`

type UpdateParams struct {
	DepartmentID *uuid.UUID
	FirstName    string
	LastName     string
	Email        string
	PhoneNumber  pgtype.Text
	Attributes   []byte
	ID           uuid.UUID
}

func (q *Queries) Update(ctx context.Context, arg UpdateParams) error {
	_, err := q.db.Exec(ctx, update,
		arg.DepartmentID,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.PhoneNumber,
		arg.Attributes,
		arg.ID,
	)
	return err
}
