// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: copyfrom.go

package sqlc

import (
	"context"
)

// iteratorForSaveMany implements pgx.CopyFromSource.
type iteratorForSaveMany struct {
	rows                 []SaveManyParams
	skippedFirstNextCall bool
}

func (r *iteratorForSaveMany) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForSaveMany) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].ID,
		r.rows[0].Label,
		r.rows[0].Attributes,
	}, nil
}

func (r iteratorForSaveMany) Err() error {
	return nil
}

func (q *Queries) SaveMany(ctx context.Context, arg []SaveManyParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"departments"}, []string{"id", "label", "attributes"}, &iteratorForSaveMany{rows: arg})
}
