// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	Count(ctx context.Context, arg CountParams) (int64, error)
	Delete(ctx context.Context, id uuid.UUID) error
	Query(ctx context.Context, arg QueryParams) ([]Department, error)
	QueryByID(ctx context.Context, id uuid.UUID) (Department, error)
	Save(ctx context.Context, arg SaveParams) error
	Update(ctx context.Context, arg UpdateParams) error
}

var _ Querier = (*Queries)(nil)
