// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type MaxAccount struct {
	ID          uuid.UUID
	AdapterID   uuid.UUID
	PhoneNumber string
	Label       string
	Status      string
	MaxUserID   pgtype.Text
	LastError   pgtype.Text
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}
