// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgconn"
)

type Querier interface {
	Count(ctx context.Context, arg CountParams) (int64, error)
	Delete(ctx context.Context, id uuid.UUID) (pgconn.CommandTag, error)
	Query(ctx context.Context, arg QueryParams) ([]MaxAccount, error)
	QueryByAdapterID(ctx context.Context, adapterID uuid.UUID) (MaxAccount, error)
	QueryByID(ctx context.Context, id uuid.UUID) (MaxAccount, error)
	Save(ctx context.Context, arg SaveParams) (MaxAccount, error)
	UpdateLabel(ctx context.Context, arg UpdateLabelParams) (MaxAccount, error)
}

var _ Querier = (*Queries)(nil)
