// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgconn"
	"github.com/jackc/pgx/v5/pgtype"
)

const count = `-- name: Count :one
SELECT COUNT(*) FROM max_accounts
WHERE
    ($1::uuid IS NULL OR id = $1)
    AND
    ($2::text IS NULL OR LOWER(label) ILIKE '%' || LOWER($2) || '%')
    AND
    ($3::text IS NULL OR phone_number ILIKE '%' || $3 || '%')
`

type CountParams struct {
	ID          *uuid.UUID
	Label       pgtype.Text
	PhoneNumber pgtype.Text
}

func (q *Queries) Count(ctx context.Context, arg CountParams) (int64, error) {
	row := q.db.QueryRow(ctx, count, arg.ID, arg.Label, arg.PhoneNumber)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const delete = `-- name: Delete :execresult
DELETE FROM max_accounts
WHERE id = $1
`

func (q *Queries) Delete(ctx context.Context, id uuid.UUID) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, delete, id)
}

const query = `-- name: Query :many
SELECT id, adapter_id, phone_number, label, status, max_user_id, last_error, created_at, updated_at FROM max_accounts
WHERE
    ($1::uuid IS NULL OR id = $1)
    AND
    ($2::text IS NULL OR LOWER(label) ILIKE '%' || LOWER($2) || '%')
    AND
    ($3::text IS NULL OR phone_number ILIKE '%' || $3 || '%')
ORDER BY created_at DESC, id DESC
LIMIT $5 OFFSET $4
`

type QueryParams struct {
	ID          *uuid.UUID
	Label       pgtype.Text
	PhoneNumber pgtype.Text
	OffsetVal   int32
	LimitVal    int32
}

func (q *Queries) Query(ctx context.Context, arg QueryParams) ([]MaxAccount, error) {
	rows, err := q.db.Query(ctx, query,
		arg.ID,
		arg.Label,
		arg.PhoneNumber,
		arg.OffsetVal,
		arg.LimitVal,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MaxAccount
	for rows.Next() {
		var i MaxAccount
		if err := rows.Scan(
			&i.ID,
			&i.AdapterID,
			&i.PhoneNumber,
			&i.Label,
			&i.Status,
			&i.MaxUserID,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const queryByAdapterID = `-- name: QueryByAdapterID :one
SELECT id, adapter_id, phone_number, label, status, max_user_id, last_error, created_at, updated_at FROM max_accounts
WHERE adapter_id = $1
`

func (q *Queries) QueryByAdapterID(ctx context.Context, adapterID uuid.UUID) (MaxAccount, error) {
	row := q.db.QueryRow(ctx, queryByAdapterID, adapterID)
	var i MaxAccount
	err := row.Scan(
		&i.ID,
		&i.AdapterID,
		&i.PhoneNumber,
		&i.Label,
		&i.Status,
		&i.MaxUserID,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const queryByID = `-- name: QueryByID :one
SELECT id, adapter_id, phone_number, label, status, max_user_id, last_error, created_at, updated_at FROM max_accounts
WHERE id = $1
`

func (q *Queries) QueryByID(ctx context.Context, id uuid.UUID) (MaxAccount, error) {
	row := q.db.QueryRow(ctx, queryByID, id)
	var i MaxAccount
	err := row.Scan(
		&i.ID,
		&i.AdapterID,
		&i.PhoneNumber,
		&i.Label,
		&i.Status,
		&i.MaxUserID,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const save = `-- name: Save :one
INSERT INTO max_accounts (
    id, adapter_id, phone_number, label, status, max_user_id,
    last_error, created_at, updated_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
ON CONFLICT (adapter_id) DO UPDATE
SET phone_number = EXCLUDED.phone_number,
    status = EXCLUDED.status,
    max_user_id = EXCLUDED.max_user_id,
    last_error = EXCLUDED.last_error,
    updated_at = EXCLUDED.updated_at
RETURNING id, adapter_id, phone_number, label, status, max_user_id, last_error, created_at, updated_at
`

type SaveParams struct {
	ID          uuid.UUID
	AdapterID   uuid.UUID
	PhoneNumber string
	Label       string
	Status      string
	MaxUserID   pgtype.Text
	LastError   pgtype.Text
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

func (q *Queries) Save(ctx context.Context, arg SaveParams) (MaxAccount, error) {
	row := q.db.QueryRow(ctx, save,
		arg.ID,
		arg.AdapterID,
		arg.PhoneNumber,
		arg.Label,
		arg.Status,
		arg.MaxUserID,
		arg.LastError,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i MaxAccount
	err := row.Scan(
		&i.ID,
		&i.AdapterID,
		&i.PhoneNumber,
		&i.Label,
		&i.Status,
		&i.MaxUserID,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateLabel = `-- name: UpdateLabel :one
UPDATE max_accounts
SET label = $2,
    updated_at = $3
WHERE id = $1
RETURNING id, adapter_id, phone_number, label, status, max_user_id, last_error, created_at, updated_at
`

type UpdateLabelParams struct {
	ID        uuid.UUID
	Label     string
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) UpdateLabel(ctx context.Context, arg UpdateLabelParams) (MaxAccount, error) {
	row := q.db.QueryRow(ctx, updateLabel, arg.ID, arg.Label, arg.UpdatedAt)
	var i MaxAccount
	err := row.Scan(
		&i.ID,
		&i.AdapterID,
		&i.PhoneNumber,
		&i.Label,
		&i.Status,
		&i.MaxUserID,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
