// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Message struct {
	ID         uuid.UUID
	Label      string
	FromEmail  string
	FromName   pgtype.Text
	Subject    pgtype.Text
	HtmlBodyID *uuid.UUID
}

type MessageAttachment struct {
	MessageID    uuid.UUID
	AttachmentID uuid.UUID
}
