// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const count = `-- name: Count :one
SELECT COUNT(*) FROM messages
WHERE
    ($1::uuid IS NULL OR id = $1) AND
    ($2::text IS NULL OR LOWER(label) ILIKE '%' || LOWER($2) || '%') AND
    ($3::text IS NULL OR LOWER(from_email) ILIKE '%' || LOWER($3) || '%') AND
    ($4::text IS NULL OR LOWER(from_name) ILIKE '%' || LOWER($4) || '%') AND
    ($5::text IS NULL OR LOWER(subject) ILIKE '%' || LOWER($5) || '%')
`

type CountParams struct {
	ID        *uuid.UUID
	Label     pgtype.Text
	FromEmail pgtype.Text
	FromName  pgtype.Text
	Subject   pgtype.Text
}

func (q *Queries) Count(ctx context.Context, arg CountParams) (int64, error) {
	row := q.db.QueryRow(ctx, count,
		arg.ID,
		arg.Label,
		arg.FromEmail,
		arg.FromName,
		arg.Subject,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const delete = `-- name: Delete :exec
DELETE FROM messages
WHERE id = $1
`

func (q *Queries) Delete(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, delete, id)
	return err
}

const query = `-- name: Query :many
SELECT id, label, from_email, from_name, subject, html_body_id FROM messages
WHERE
    -- Точный поиск по ID (если передан)
    ($1::uuid IS NULL OR id = $1)
    AND
    -- Поиск по label
    ($2::text IS NULL OR LOWER(label) ILIKE '%' || LOWER($2) || '%')
    AND
    -- Поиск по email отправителя
    ($3::text IS NULL OR LOWER(from_email) ILIKE '%' || LOWER($3) || '%')
    AND
    -- Поиск по имени отправителя
    ($4::text IS NULL OR LOWER(from_name) ILIKE '%' || LOWER($4) || '%')
    AND
    -- Поиск по теме
    ($5::text IS NULL OR LOWER(subject) ILIKE '%' || LOWER($5) || '%')
ORDER BY
    -- Сортировка напрямую по бизнес-константам (a=ID, b=Label, c=Email, d=FromName, e=Subject)
    CASE WHEN $6::text = 'a_asc' THEN id::text END ASC,
    CASE WHEN $6::text = 'a_desc' THEN id::text END DESC,
    CASE WHEN $6::text = 'b_asc' THEN label END ASC,
    CASE WHEN $6::text = 'b_desc' THEN label END DESC,
    CASE WHEN $6::text = 'c_asc' THEN from_email END ASC,
    CASE WHEN $6::text = 'c_desc' THEN from_email END DESC,
    CASE WHEN $6::text = 'd_asc' THEN from_name END ASC,
    CASE WHEN $6::text = 'd_desc' THEN from_name END DESC,
    CASE WHEN $6::text = 'e_asc' THEN subject END ASC,
    CASE WHEN $6::text = 'e_desc' THEN subject END DESC
LIMIT $8 OFFSET $7
`

type QueryParams struct {
	ID        *uuid.UUID
	Label     pgtype.Text
	FromEmail pgtype.Text
	FromName  pgtype.Text
	Subject   pgtype.Text
	OrderBy   string
	OffsetVal int32
	LimitVal  int32
}

func (q *Queries) Query(ctx context.Context, arg QueryParams) ([]Message, error) {
	rows, err := q.db.Query(ctx, query,
		arg.ID,
		arg.Label,
		arg.FromEmail,
		arg.FromName,
		arg.Subject,
		arg.OrderBy,
		arg.OffsetVal,
		arg.LimitVal,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.Label,
			&i.FromEmail,
			&i.FromName,
			&i.Subject,
			&i.HtmlBodyID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const queryAttachments = `-- name: QueryAttachments :many
SELECT attachment_id FROM message_attachments WHERE message_id = $1
`

func (q *Queries) QueryAttachments(ctx context.Context, messageID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, queryAttachments, messageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var attachment_id uuid.UUID
		if err := rows.Scan(&attachment_id); err != nil {
			return nil, err
		}
		items = append(items, attachment_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const queryAttachmentsByMessageIDs = `-- name: QueryAttachmentsByMessageIDs :many
SELECT message_id, attachment_id FROM message_attachments
WHERE message_id = ANY($1::uuid[])
`

func (q *Queries) QueryAttachmentsByMessageIDs(ctx context.Context, messageIds []uuid.UUID) ([]MessageAttachment, error) {
	rows, err := q.db.Query(ctx, queryAttachmentsByMessageIDs, messageIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MessageAttachment
	for rows.Next() {
		var i MessageAttachment
		if err := rows.Scan(&i.MessageID, &i.AttachmentID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const queryByID = `-- name: QueryByID :one
SELECT id, label, from_email, from_name, subject, html_body_id FROM messages
WHERE id = $1
`

func (q *Queries) QueryByID(ctx context.Context, id uuid.UUID) (Message, error) {
	row := q.db.QueryRow(ctx, queryByID, id)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.Label,
		&i.FromEmail,
		&i.FromName,
		&i.Subject,
		&i.HtmlBodyID,
	)
	return i, err
}

const save = `-- name: Save :exec
INSERT INTO messages (
    id,
    label,
    from_email,
    from_name,
    subject,
    html_body_id
) VALUES (
    $1, $2, $3, $4, $5, $6
)
`

type SaveParams struct {
	ID         uuid.UUID
	Label      string
	FromEmail  string
	FromName   pgtype.Text
	Subject    pgtype.Text
	HtmlBodyID *uuid.UUID
}

func (q *Queries) Save(ctx context.Context, arg SaveParams) error {
	_, err := q.db.Exec(ctx, save,
		arg.ID,
		arg.Label,
		arg.FromEmail,
		arg.FromName,
		arg.Subject,
		arg.HtmlBodyID,
	)
	return err
}

const syncAttachments = `-- name: SyncAttachments :exec
WITH new_attachments AS (
    SELECT $1::uuid AS message_id, 
           unnest($2::uuid[]) AS attachment_id
),
inserted AS (
    INSERT INTO message_attachments (message_id, attachment_id)
    SELECT message_id, attachment_id FROM new_attachments
    ON CONFLICT ON CONSTRAINT message_attachments_pkey DO NOTHING
)
DELETE FROM message_attachments ma
WHERE ma.message_id = $1
  AND ma.attachment_id NOT IN (
      SELECT attachment_id FROM new_attachments
)
`

type SyncAttachmentsParams struct {
	MessageID     uuid.UUID
	AttachmentIds []uuid.UUID
}

func (q *Queries) SyncAttachments(ctx context.Context, arg SyncAttachmentsParams) error {
	_, err := q.db.Exec(ctx, syncAttachments, arg.MessageID, arg.AttachmentIds)
	return err
}

const update = `-- name: Update :exec
UPDATE messages
SET
    label = $1,
    from_email = $2,
    from_name = $3,
    subject = $4,
    html_body_id = $5
WHERE id = $6
`

type UpdateParams struct {
	Label      string
	FromEmail  string
	FromName   pgtype.Text
	Subject    pgtype.Text
	HtmlBodyID *uuid.UUID
	ID         uuid.UUID
}

func (q *Queries) Update(ctx context.Context, arg UpdateParams) error {
	_, err := q.db.Exec(ctx, update,
		arg.Label,
		arg.FromEmail,
		arg.FromName,
		arg.Subject,
		arg.HtmlBodyID,
		arg.ID,
	)
	return err
}
