// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type MaxAdapterProcessedEvent struct {
	Seq         int64
	ProcessedAt pgtype.Timestamptz
}

type MaxDelivery struct {
	ID                uuid.UUID
	TargetID          uuid.UUID
	CampaignID        uuid.UUID
	EmployeeID        uuid.UUID
	MaxAccountID      uuid.UUID
	AdapterAccountID  uuid.UUID
	ChatID            string
	MessageID         string
	SentAt            pgtype.Timestamptz
	ReadAt            pgtype.Timestamptz
	RepliedAt         pgtype.Timestamptz
	EducationSentAt   pgtype.Timestamptz
	IncomingMessageID string
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
}
