// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgconn"
	"github.com/jackc/pgx/v5/pgtype"
)

const isProcessed = `-- name: IsProcessed :one
SELECT EXISTS(SELECT 1 FROM max_adapter_processed_events WHERE seq = $1)
`

func (q *Queries) IsProcessed(ctx context.Context, seq int64) (bool, error) {
	row := q.db.QueryRow(ctx, isProcessed, seq)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const markEducationSent = `-- name: MarkEducationSent :exec
UPDATE max_deliveries
SET education_sent_at = COALESCE(education_sent_at, $2),
    updated_at = $2
WHERE id = $1
`

type MarkEducationSentParams struct {
	ID        uuid.UUID
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) MarkEducationSent(ctx context.Context, arg MarkEducationSentParams) error {
	_, err := q.db.Exec(ctx, markEducationSent, arg.ID, arg.UpdatedAt)
	return err
}

const markProcessed = `-- name: MarkProcessed :exec
INSERT INTO max_adapter_processed_events (seq, processed_at)
VALUES ($1, $2)
ON CONFLICT (seq) DO NOTHING
`

type MarkProcessedParams struct {
	Seq         int64
	ProcessedAt pgtype.Timestamptz
}

func (q *Queries) MarkProcessed(ctx context.Context, arg MarkProcessedParams) error {
	_, err := q.db.Exec(ctx, markProcessed, arg.Seq, arg.ProcessedAt)
	return err
}

const markRead = `-- name: MarkRead :execresult
UPDATE max_deliveries
SET read_at = $2, updated_at = $2
WHERE id = $1 AND read_at IS NULL
`

type MarkReadParams struct {
	ID     uuid.UUID
	ReadAt pgtype.Timestamptz
}

func (q *Queries) MarkRead(ctx context.Context, arg MarkReadParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, markRead, arg.ID, arg.ReadAt)
}

const markReplied = `-- name: MarkReplied :execresult
UPDATE max_deliveries
SET replied_at = $2,
    incoming_message_id = $3,
    updated_at = $2
WHERE id = $1 AND replied_at IS NULL
`

type MarkRepliedParams struct {
	ID                uuid.UUID
	RepliedAt         pgtype.Timestamptz
	IncomingMessageID string
}

func (q *Queries) MarkReplied(ctx context.Context, arg MarkRepliedParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, markReplied, arg.ID, arg.RepliedAt, arg.IncomingMessageID)
}

const queryByID = `-- name: QueryByID :one
SELECT id, target_id, campaign_id, employee_id, max_account_id, adapter_account_id, chat_id, message_id, sent_at, read_at, replied_at, education_sent_at, incoming_message_id, created_at, updated_at FROM max_deliveries WHERE id = $1
`

func (q *Queries) QueryByID(ctx context.Context, id uuid.UUID) (MaxDelivery, error) {
	row := q.db.QueryRow(ctx, queryByID, id)
	var i MaxDelivery
	err := row.Scan(
		&i.ID,
		&i.TargetID,
		&i.CampaignID,
		&i.EmployeeID,
		&i.MaxAccountID,
		&i.AdapterAccountID,
		&i.ChatID,
		&i.MessageID,
		&i.SentAt,
		&i.ReadAt,
		&i.RepliedAt,
		&i.EducationSentAt,
		&i.IncomingMessageID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const queryByMessage = `-- name: QueryByMessage :one
SELECT id, target_id, campaign_id, employee_id, max_account_id, adapter_account_id, chat_id, message_id, sent_at, read_at, replied_at, education_sent_at, incoming_message_id, created_at, updated_at FROM max_deliveries
WHERE adapter_account_id = $1 AND chat_id = $2 AND message_id = $3
`

type QueryByMessageParams struct {
	AdapterAccountID uuid.UUID
	ChatID           string
	MessageID        string
}

func (q *Queries) QueryByMessage(ctx context.Context, arg QueryByMessageParams) (MaxDelivery, error) {
	row := q.db.QueryRow(ctx, queryByMessage, arg.AdapterAccountID, arg.ChatID, arg.MessageID)
	var i MaxDelivery
	err := row.Scan(
		&i.ID,
		&i.TargetID,
		&i.CampaignID,
		&i.EmployeeID,
		&i.MaxAccountID,
		&i.AdapterAccountID,
		&i.ChatID,
		&i.MessageID,
		&i.SentAt,
		&i.ReadAt,
		&i.RepliedAt,
		&i.EducationSentAt,
		&i.IncomingMessageID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const queryLatestByChat = `-- name: QueryLatestByChat :one
SELECT id, target_id, campaign_id, employee_id, max_account_id, adapter_account_id, chat_id, message_id, sent_at, read_at, replied_at, education_sent_at, incoming_message_id, created_at, updated_at FROM max_deliveries
WHERE adapter_account_id = $1 AND chat_id = $2
ORDER BY sent_at DESC, created_at DESC
LIMIT 1
`

type QueryLatestByChatParams struct {
	AdapterAccountID uuid.UUID
	ChatID           string
}

func (q *Queries) QueryLatestByChat(ctx context.Context, arg QueryLatestByChatParams) (MaxDelivery, error) {
	row := q.db.QueryRow(ctx, queryLatestByChat, arg.AdapterAccountID, arg.ChatID)
	var i MaxDelivery
	err := row.Scan(
		&i.ID,
		&i.TargetID,
		&i.CampaignID,
		&i.EmployeeID,
		&i.MaxAccountID,
		&i.AdapterAccountID,
		&i.ChatID,
		&i.MessageID,
		&i.SentAt,
		&i.ReadAt,
		&i.RepliedAt,
		&i.EducationSentAt,
		&i.IncomingMessageID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const queryLatestUnreadByChat = `-- name: QueryLatestUnreadByChat :one
SELECT id, target_id, campaign_id, employee_id, max_account_id, adapter_account_id, chat_id, message_id, sent_at, read_at, replied_at, education_sent_at, incoming_message_id, created_at, updated_at FROM max_deliveries
WHERE adapter_account_id = $1 AND chat_id = $2 AND read_at IS NULL
ORDER BY sent_at DESC, created_at DESC
LIMIT 1
`

type QueryLatestUnreadByChatParams struct {
	AdapterAccountID uuid.UUID
	ChatID           string
}

func (q *Queries) QueryLatestUnreadByChat(ctx context.Context, arg QueryLatestUnreadByChatParams) (MaxDelivery, error) {
	row := q.db.QueryRow(ctx, queryLatestUnreadByChat, arg.AdapterAccountID, arg.ChatID)
	var i MaxDelivery
	err := row.Scan(
		&i.ID,
		&i.TargetID,
		&i.CampaignID,
		&i.EmployeeID,
		&i.MaxAccountID,
		&i.AdapterAccountID,
		&i.ChatID,
		&i.MessageID,
		&i.SentAt,
		&i.ReadAt,
		&i.RepliedAt,
		&i.EducationSentAt,
		&i.IncomingMessageID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const saveSent = `-- name: SaveSent :exec
INSERT INTO max_deliveries (
    id, target_id, campaign_id, employee_id, max_account_id,
    adapter_account_id, chat_id, message_id, sent_at, created_at, updated_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
ON CONFLICT (target_id) DO UPDATE
SET adapter_account_id = EXCLUDED.adapter_account_id,
    chat_id = EXCLUDED.chat_id,
    message_id = EXCLUDED.message_id,
    sent_at = EXCLUDED.sent_at,
    updated_at = EXCLUDED.updated_at
`

type SaveSentParams struct {
	ID               uuid.UUID
	TargetID         uuid.UUID
	CampaignID       uuid.UUID
	EmployeeID       uuid.UUID
	MaxAccountID     uuid.UUID
	AdapterAccountID uuid.UUID
	ChatID           string
	MessageID        string
	SentAt           pgtype.Timestamptz
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

func (q *Queries) SaveSent(ctx context.Context, arg SaveSentParams) error {
	_, err := q.db.Exec(ctx, saveSent,
		arg.ID,
		arg.TargetID,
		arg.CampaignID,
		arg.EmployeeID,
		arg.MaxAccountID,
		arg.AdapterAccountID,
		arg.ChatID,
		arg.MessageID,
		arg.SentAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
