// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgconn"
)

type Querier interface {
	IsProcessed(ctx context.Context, seq int64) (bool, error)
	MarkEducationSent(ctx context.Context, arg MarkEducationSentParams) error
	MarkProcessed(ctx context.Context, arg MarkProcessedParams) error
	MarkRead(ctx context.Context, arg MarkReadParams) (pgconn.CommandTag, error)
	MarkReplied(ctx context.Context, arg MarkRepliedParams) (pgconn.CommandTag, error)
	QueryByID(ctx context.Context, id uuid.UUID) (MaxDelivery, error)
	QueryByMessage(ctx context.Context, arg QueryByMessageParams) (MaxDelivery, error)
	QueryLatestByChat(ctx context.Context, arg QueryLatestByChatParams) (MaxDelivery, error)
	QueryLatestUnreadByChat(ctx context.Context, arg QueryLatestUnreadByChatParams) (MaxDelivery, error)
	SaveSent(ctx context.Context, arg SaveSentParams) error
}

var _ Querier = (*Queries)(nil)
