// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/google/uuid"
)

type Landing struct {
	ID         uuid.UUID
	Label      string
	HtmlBodyID *uuid.UUID
}
