// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const count = `-- name: Count :one
SELECT COUNT(*) FROM landings
WHERE
    ($1::uuid IS NULL OR id = $1)
    AND
    ($2::text IS NULL OR LOWER(label) ILIKE '%' || LOWER($2) || '%')
`

type CountParams struct {
	ID    *uuid.UUID
	Label pgtype.Text
}

func (q *Queries) Count(ctx context.Context, arg CountParams) (int64, error) {
	row := q.db.QueryRow(ctx, count, arg.ID, arg.Label)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const delete = `-- name: Delete :exec
DELETE FROM landings
WHERE id = $1
`

func (q *Queries) Delete(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, delete, id)
	return err
}

const query = `-- name: Query :many
SELECT id, label, content_path, required_vars FROM landings
WHERE
    ($1::uuid IS NULL OR id = $1)
    AND
    ($2::text IS NULL OR LOWER(label) ILIKE '%' || LOWER($2) || '%')
ORDER BY
    CASE WHEN $3::text = 'a_asc' THEN id::text END ASC,
    CASE WHEN $3::text = 'a_desc' THEN id::text END DESC,
    CASE WHEN $3::text = 'b_asc' THEN label END ASC,
    CASE WHEN $3::text = 'b_desc' THEN label END DESC,
    id DESC
LIMIT $5 OFFSET $4
`

type QueryParams struct {
	ID        *uuid.UUID
	Label     pgtype.Text
	OrderBy   string
	OffsetVal int32
	LimitVal  int32
}

func (q *Queries) Query(ctx context.Context, arg QueryParams) ([]Landing, error) {
	rows, err := q.db.Query(ctx, query,
		arg.ID,
		arg.Label,
		arg.OrderBy,
		arg.OffsetVal,
		arg.LimitVal,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Landing
	for rows.Next() {
		var i Landing
		if err := rows.Scan(
			&i.ID,
			&i.Label,
			&i.ContentPath,
			&i.RequiredVars,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const queryByID = `-- name: QueryByID :one
SELECT id, label, content_path, required_vars FROM landings
WHERE id = $1
`

func (q *Queries) QueryByID(ctx context.Context, id uuid.UUID) (Landing, error) {
	row := q.db.QueryRow(ctx, queryByID, id)
	var i Landing
	err := row.Scan(
		&i.ID,
		&i.Label,
		&i.ContentPath,
		&i.RequiredVars,
	)
	return i, err
}

const save = `-- name: Save :exec
INSERT INTO landings (
    id,
    label,
    content_path,
    required_vars
) VALUES (
    $1, $2, $3, $4
)
`

type SaveParams struct {
	ID           uuid.UUID
	Label        string
	ContentPath  pgtype.Text
	RequiredVars []string
}

func (q *Queries) Save(ctx context.Context, arg SaveParams) error {
	_, err := q.db.Exec(ctx, save,
		arg.ID,
		arg.Label,
		arg.ContentPath,
		arg.RequiredVars,
	)
	return err
}

const update = `-- name: Update :exec
UPDATE landings
SET
    label = $1,
    content_path = $2,
    required_vars = $3
WHERE id = $4
`

type UpdateParams struct {
	Label        string
	ContentPath  pgtype.Text
	RequiredVars []string
	ID           uuid.UUID
}

func (q *Queries) Update(ctx context.Context, arg UpdateParams) error {
	_, err := q.db.Exec(ctx, update,
		arg.Label,
		arg.ContentPath,
		arg.RequiredVars,
		arg.ID,
	)
	return err
}
