// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Event struct {
	ID         uuid.UUID
	CampaignID uuid.UUID
	EmployeeID uuid.UUID
	Type       string
	OccurredAt pgtype.Timestamp
}
