// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"
)

type Querier interface {
	SaveEvent(ctx context.Context, arg SaveEventParams) error
}

var _ Querier = (*Queries)(nil)
