// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const saveEvent = `-- name: SaveEvent :exec
INSERT INTO events (id, campaign_id, employee_id, type, occurred_at)
VALUES ($1, $2, $3, $4, $5)
`

type SaveEventParams struct {
	ID         uuid.UUID
	CampaignID uuid.UUID
	EmployeeID uuid.UUID
	Type       string
	OccurredAt pgtype.Timestamp
}

func (q *Queries) SaveEvent(ctx context.Context, arg SaveEventParams) error {
	_, err := q.db.Exec(ctx, saveEvent,
		arg.ID,
		arg.CampaignID,
		arg.EmployeeID,
		arg.Type,
		arg.OccurredAt,
	)
	return err
}
