// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Campaign struct {
	ID     uuid.UUID
	Status string
}

type Target struct {
	ID          uuid.UUID
	Token       string
	EmployeeID  uuid.UUID
	CampaignID  uuid.UUID
	Status      string
	ScheduledAt pgtype.Timestamptz
	CreatedAt   pgtype.Timestamptz
}
