// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const count = `-- name: Count :one
SELECT COUNT(*) FROM targets
WHERE
    ($1::uuid IS NULL OR id = $1)
AND
    ($2::uuid IS NULL OR campaign_id = $2)
AND
    ($3::uuid IS NULL OR employee_id = $3)
AND
    ($4::text IS NULL OR status = $4)
AND
    ($5::boolean IS NULL
        OR ($5 = true AND scheduled_at IS NOT NULL)
        OR ($5 = false AND scheduled_at IS NULL))
`

type CountParams struct {
	ID          *uuid.UUID
	CampaignID  *uuid.UUID
	EmployeeID  *uuid.UUID
	Status      pgtype.Text
	HasSchedule pgtype.Bool
}

func (q *Queries) Count(ctx context.Context, arg CountParams) (int64, error) {
	row := q.db.QueryRow(ctx, count,
		arg.ID,
		arg.CampaignID,
		arg.EmployeeID,
		arg.Status,
		arg.HasSchedule,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const delete = `-- name: Delete :exec
DELETE FROM targets
WHERE id = $1
`

func (q *Queries) Delete(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, delete, id)
	return err
}

const deleteByCampaignID = `-- name: DeleteByCampaignID :exec
DELETE FROM targets
WHERE campaign_id = $1
`

func (q *Queries) DeleteByCampaignID(ctx context.Context, campaignID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteByCampaignID, campaignID)
	return err
}

const query = `-- name: Query :many
SELECT id, token, employee_id, campaign_id, status, scheduled_at, created_at FROM targets
WHERE
    ($1::uuid IS NULL OR id = $1)
AND
    ($2::uuid IS NULL OR campaign_id = $2)
AND
    ($3::uuid IS NULL OR employee_id = $3)
AND
    ($4::text IS NULL OR status = $4)
AND
    ($5::boolean IS NULL
        OR ($5 = true AND scheduled_at IS NOT NULL)
        OR ($5 = false AND scheduled_at IS NULL))
ORDER BY created_at ASC, id ASC
`

type QueryParams struct {
	ID          *uuid.UUID
	CampaignID  *uuid.UUID
	EmployeeID  *uuid.UUID
	Status      pgtype.Text
	HasSchedule pgtype.Bool
}

func (q *Queries) Query(ctx context.Context, arg QueryParams) ([]Target, error) {
	rows, err := q.db.Query(ctx, query,
		arg.ID,
		arg.CampaignID,
		arg.EmployeeID,
		arg.Status,
		arg.HasSchedule,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Target
	for rows.Next() {
		var i Target
		if err := rows.Scan(
			&i.ID,
			&i.Token,
			&i.EmployeeID,
			&i.CampaignID,
			&i.Status,
			&i.ScheduledAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const queryByID = `-- name: QueryByID :one
SELECT id, token, employee_id, campaign_id, status, scheduled_at, created_at FROM targets
WHERE id = $1
`

func (q *Queries) QueryByID(ctx context.Context, id uuid.UUID) (Target, error) {
	row := q.db.QueryRow(ctx, queryByID, id)
	var i Target
	err := row.Scan(
		&i.ID,
		&i.Token,
		&i.EmployeeID,
		&i.CampaignID,
		&i.Status,
		&i.ScheduledAt,
		&i.CreatedAt,
	)
	return i, err
}

const queryDue = `-- name: QueryDue :many
SELECT targets.id, targets.token, targets.employee_id, targets.campaign_id, targets.status, targets.scheduled_at, targets.created_at FROM targets
JOIN campaigns ON campaigns.id = targets.campaign_id
WHERE
    targets.status = 'PENDING'
    AND targets.scheduled_at IS NOT NULL
    AND targets.scheduled_at <= $1
    AND campaigns.status = 'ACTIVE'
ORDER BY targets.scheduled_at ASC, targets.created_at ASC, targets.id ASC
`

func (q *Queries) QueryDue(ctx context.Context, scheduledAt pgtype.Timestamptz) ([]Target, error) {
	rows, err := q.db.Query(ctx, queryDue, scheduledAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Target
	for rows.Next() {
		var i Target
		if err := rows.Scan(
			&i.ID,
			&i.Token,
			&i.EmployeeID,
			&i.CampaignID,
			&i.Status,
			&i.ScheduledAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const save = `-- name: Save :exec
INSERT INTO targets (
    id,
    token,
    employee_id,
    campaign_id,
    status,
    scheduled_at,
    created_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
`

type SaveParams struct {
	ID          uuid.UUID
	Token       string
	EmployeeID  uuid.UUID
	CampaignID  uuid.UUID
	Status      string
	ScheduledAt pgtype.Timestamptz
	CreatedAt   pgtype.Timestamptz
}

func (q *Queries) Save(ctx context.Context, arg SaveParams) error {
	_, err := q.db.Exec(ctx, save,
		arg.ID,
		arg.Token,
		arg.EmployeeID,
		arg.CampaignID,
		arg.Status,
		arg.ScheduledAt,
		arg.CreatedAt,
	)
	return err
}

const update = `-- name: Update :exec
UPDATE targets
SET
    token = $1,
    employee_id = $2,
    campaign_id = $3,
    status = $4,
    scheduled_at = $5,
    created_at = $6
WHERE id = $7
`

type UpdateParams struct {
	Token       string
	EmployeeID  uuid.UUID
	CampaignID  uuid.UUID
	Status      string
	ScheduledAt pgtype.Timestamptz
	CreatedAt   pgtype.Timestamptz
	ID          uuid.UUID
}

func (q *Queries) Update(ctx context.Context, arg UpdateParams) error {
	_, err := q.db.Exec(ctx, update,
		arg.Token,
		arg.EmployeeID,
		arg.CampaignID,
		arg.Status,
		arg.ScheduledAt,
		arg.CreatedAt,
		arg.ID,
	)
	return err
}

const updateMany = `-- name: UpdateMany :exec
UPDATE targets
SET
    token        = data.token,
    employee_id  = data.employee_id,
    campaign_id  = data.campaign_id,
    status       = data.status,
    scheduled_at = data.scheduled_at,
    created_at   = data.created_at
FROM (
    SELECT
        UNNEST($1::uuid[])          AS id,
        UNNEST($2::text[])       AS token,
        UNNEST($3::uuid[]) AS employee_id,
        UNNEST($4::uuid[]) AS campaign_id,
        UNNEST($5::text[])     AS status,
        UNNEST($6::timestamptz[]) AS scheduled_at,
        UNNEST($7::timestamptz[])   AS created_at
) AS data
WHERE targets.id = data.id
`

type UpdateManyParams struct {
	Ids          []uuid.UUID
	Tokens       []string
	EmployeeIds  []uuid.UUID
	CampaignIds  []uuid.UUID
	Statuses     []string
	ScheduledAts []pgtype.Timestamptz
	CreatedAts   []pgtype.Timestamptz
}

func (q *Queries) UpdateMany(ctx context.Context, arg UpdateManyParams) error {
	_, err := q.db.Exec(ctx, updateMany,
		arg.Ids,
		arg.Tokens,
		arg.EmployeeIds,
		arg.CampaignIds,
		arg.Statuses,
		arg.ScheduledAts,
		arg.CreatedAts,
	)
	return err
}
