// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Admin struct {
	ID           uuid.UUID
	FirstName    string
	LastName     string
	Login        string
	PasswordHash string
	CreatedAt    pgtype.Timestamptz
}
