// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	Count(ctx context.Context, arg CountParams) (int64, error)
	Query(ctx context.Context, arg QueryParams) ([]Admin, error)
	QueryByID(ctx context.Context, id uuid.UUID) (Admin, error)
	QueryByLogin(ctx context.Context, login string) (Admin, error)
	Save(ctx context.Context, arg SaveParams) error
	Update(ctx context.Context, arg UpdateParams) error
}

var _ Querier = (*Queries)(nil)
