// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const count = `-- name: Count :one
SELECT COUNT(*) FROM admins
WHERE
    ($1::text IS NULL OR LOWER(login) ILIKE '%' || LOWER($1) || '%')
    AND
    ($2::text IS NULL OR LOWER(first_name || ' ' || last_name) ILIKE '%' || LOWER($2) || '%')
`

type CountParams struct {
	Login    pgtype.Text
	FullName pgtype.Text
}

func (q *Queries) Count(ctx context.Context, arg CountParams) (int64, error) {
	row := q.db.QueryRow(ctx, count, arg.Login, arg.FullName)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const query = `-- name: Query :many
SELECT id, first_name, last_name, login, password_hash, created_at FROM admins
WHERE
    ($1::text IS NULL OR LOWER(login) ILIKE '%' || LOWER($1) || '%')
    AND
    ($2::text IS NULL OR LOWER(first_name || ' ' || last_name) ILIKE '%' || LOWER($2) || '%')
`

type QueryParams struct {
	Login    pgtype.Text
	FullName pgtype.Text
}

func (q *Queries) Query(ctx context.Context, arg QueryParams) ([]Admin, error) {
	rows, err := q.db.Query(ctx, query, arg.Login, arg.FullName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Admin
	for rows.Next() {
		var i Admin
		if err := rows.Scan(
			&i.ID,
			&i.FirstName,
			&i.LastName,
			&i.Login,
			&i.PasswordHash,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const queryByID = `-- name: QueryByID :one
SELECT id, first_name, last_name, login, password_hash, created_at FROM admins
WHERE id = $1
`

func (q *Queries) QueryByID(ctx context.Context, id uuid.UUID) (Admin, error) {
	row := q.db.QueryRow(ctx, queryByID, id)
	var i Admin
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Login,
		&i.PasswordHash,
		&i.CreatedAt,
	)
	return i, err
}

const queryByLogin = `-- name: QueryByLogin :one
SELECT id, first_name, last_name, login, password_hash, created_at FROM admins
WHERE login = $1
`

func (q *Queries) QueryByLogin(ctx context.Context, login string) (Admin, error) {
	row := q.db.QueryRow(ctx, queryByLogin, login)
	var i Admin
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Login,
		&i.PasswordHash,
		&i.CreatedAt,
	)
	return i, err
}

const save = `-- name: Save :exec
INSERT INTO admins (
    id,
    first_name,
    last_name,
    login,
    password_hash,
    created_at
) VALUES (
    $1, $2, $3, $4, $5, $6
)
`

type SaveParams struct {
	ID           uuid.UUID
	FirstName    string
	LastName     string
	Login        string
	PasswordHash string
	CreatedAt    pgtype.Timestamptz
}

func (q *Queries) Save(ctx context.Context, arg SaveParams) error {
	_, err := q.db.Exec(ctx, save,
		arg.ID,
		arg.FirstName,
		arg.LastName,
		arg.Login,
		arg.PasswordHash,
		arg.CreatedAt,
	)
	return err
}

const update = `-- name: Update :exec
UPDATE admins
SET
    first_name = $1,
    last_name = $2,
    login = $3,
    password_hash = $4
WHERE id = $5
`

type UpdateParams struct {
	FirstName    string
	LastName     string
	Login        string
	PasswordHash string
	ID           uuid.UUID
}

func (q *Queries) Update(ctx context.Context, arg UpdateParams) error {
	_, err := q.db.Exec(ctx, update,
		arg.FirstName,
		arg.LastName,
		arg.Login,
		arg.PasswordHash,
		arg.ID,
	)
	return err
}
