// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	DeleteExpired(ctx context.Context, expiresAt pgtype.Timestamptz) error
	QueryByTokenHash(ctx context.Context, tokenHash string) (Session, error)
	Revoke(ctx context.Context, arg RevokeParams) error
	RevokeByAdminID(ctx context.Context, arg RevokeByAdminIDParams) error
	Save(ctx context.Context, arg SaveParams) error
}

var _ Querier = (*Queries)(nil)
