// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package sqlc

import (
	"context"
	"net/netip"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const deleteExpired = `-- name: DeleteExpired :exec
DELETE FROM sessions
WHERE expires_at <= $1
`

func (q *Queries) DeleteExpired(ctx context.Context, expiresAt pgtype.Timestamptz) error {
	_, err := q.db.Exec(ctx, deleteExpired, expiresAt)
	return err
}

const queryByTokenHash = `-- name: QueryByTokenHash :one
SELECT id, admin_id, token_hash, csrf_token, created_at, expires_at, revoked_at, ip_address, user_agent FROM sessions
WHERE token_hash = $1
`

func (q *Queries) QueryByTokenHash(ctx context.Context, tokenHash string) (Session, error) {
	row := q.db.QueryRow(ctx, queryByTokenHash, tokenHash)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.AdminID,
		&i.TokenHash,
		&i.CsrfToken,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.IpAddress,
		&i.UserAgent,
	)
	return i, err
}

const revoke = `-- name: Revoke :exec
UPDATE sessions
SET revoked_at = $2
WHERE id = $1 AND revoked_at IS NULL
`

type RevokeParams struct {
	ID        uuid.UUID
	RevokedAt pgtype.Timestamptz
}

func (q *Queries) Revoke(ctx context.Context, arg RevokeParams) error {
	_, err := q.db.Exec(ctx, revoke, arg.ID, arg.RevokedAt)
	return err
}

const revokeByAdminID = `-- name: RevokeByAdminID :exec
UPDATE sessions
SET revoked_at = $2
WHERE admin_id = $1 AND revoked_at IS NULL
`

type RevokeByAdminIDParams struct {
	AdminID   uuid.UUID
	RevokedAt pgtype.Timestamptz
}

func (q *Queries) RevokeByAdminID(ctx context.Context, arg RevokeByAdminIDParams) error {
	_, err := q.db.Exec(ctx, revokeByAdminID, arg.AdminID, arg.RevokedAt)
	return err
}

const save = `-- name: Save :exec
INSERT INTO sessions (
    id,
    admin_id,
    token_hash,
    csrf_token,
    created_at,
    expires_at,
    revoked_at,
    ip_address,
    user_agent
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
)
`

type SaveParams struct {
	ID        uuid.UUID
	AdminID   uuid.UUID
	TokenHash string
	CsrfToken string
	CreatedAt pgtype.Timestamptz
	ExpiresAt pgtype.Timestamptz
	RevokedAt pgtype.Timestamptz
	IpAddress *netip.Addr
	UserAgent pgtype.Text
}

func (q *Queries) Save(ctx context.Context, arg SaveParams) error {
	_, err := q.db.Exec(ctx, save,
		arg.ID,
		arg.AdminID,
		arg.TokenHash,
		arg.CsrfToken,
		arg.CreatedAt,
		arg.ExpiresAt,
		arg.RevokedAt,
		arg.IpAddress,
		arg.UserAgent,
	)
	return err
}
