// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	Delete(ctx context.Context, id uuid.UUID) error
	DeleteByCampaignID(ctx context.Context, campaignID uuid.UUID) error
	QueryByCampaignID(ctx context.Context, campaignID uuid.UUID) ([]Target, error)
	QueryByID(ctx context.Context, id uuid.UUID) (Target, error)
	QueryDue(ctx context.Context, scheduledAt pgtype.Timestamptz) ([]Target, error)
	Save(ctx context.Context, arg SaveParams) error
	Update(ctx context.Context, arg UpdateParams) error
}

var _ Querier = (*Queries)(nil)
