// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const delete = `-- name: Delete :exec
DELETE FROM targets
WHERE id = $1
`

func (q *Queries) Delete(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, delete, id)
	return err
}

const deleteByCampaignID = `-- name: DeleteByCampaignID :exec
DELETE FROM targets
WHERE campaign_id = $1
`

func (q *Queries) DeleteByCampaignID(ctx context.Context, campaignID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteByCampaignID, campaignID)
	return err
}

const queryByCampaignID = `-- name: QueryByCampaignID :many
SELECT id, token, employee_id, campaign_id, status, scheduled_at, created_at FROM targets
WHERE campaign_id = $1
ORDER BY created_at ASC, id ASC
`

func (q *Queries) QueryByCampaignID(ctx context.Context, campaignID uuid.UUID) ([]Target, error) {
	rows, err := q.db.Query(ctx, queryByCampaignID, campaignID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Target
	for rows.Next() {
		var i Target
		if err := rows.Scan(
			&i.ID,
			&i.Token,
			&i.EmployeeID,
			&i.CampaignID,
			&i.Status,
			&i.ScheduledAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const queryByID = `-- name: QueryByID :one
SELECT id, token, employee_id, campaign_id, status, scheduled_at, created_at FROM targets
WHERE id = $1
`

func (q *Queries) QueryByID(ctx context.Context, id uuid.UUID) (Target, error) {
	row := q.db.QueryRow(ctx, queryByID, id)
	var i Target
	err := row.Scan(
		&i.ID,
		&i.Token,
		&i.EmployeeID,
		&i.CampaignID,
		&i.Status,
		&i.ScheduledAt,
		&i.CreatedAt,
	)
	return i, err
}

const queryDue = `-- name: QueryDue :many
SELECT id, token, employee_id, campaign_id, status, scheduled_at, created_at FROM targets
WHERE
    status = 'PENDING'
    AND scheduled_at IS NOT NULL
    AND scheduled_at <= $1
ORDER BY scheduled_at ASC, created_at ASC, id ASC
`

func (q *Queries) QueryDue(ctx context.Context, scheduledAt pgtype.Timestamptz) ([]Target, error) {
	rows, err := q.db.Query(ctx, queryDue, scheduledAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Target
	for rows.Next() {
		var i Target
		if err := rows.Scan(
			&i.ID,
			&i.Token,
			&i.EmployeeID,
			&i.CampaignID,
			&i.Status,
			&i.ScheduledAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const save = `-- name: Save :exec
INSERT INTO targets (
    id,
    token,
    employee_id,
    campaign_id,
    status,
    scheduled_at,
    created_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
`

type SaveParams struct {
	ID          uuid.UUID
	Token       string
	EmployeeID  uuid.UUID
	CampaignID  uuid.UUID
	Status      string
	ScheduledAt pgtype.Timestamptz
	CreatedAt   pgtype.Timestamptz
}

func (q *Queries) Save(ctx context.Context, arg SaveParams) error {
	_, err := q.db.Exec(ctx, save,
		arg.ID,
		arg.Token,
		arg.EmployeeID,
		arg.CampaignID,
		arg.Status,
		arg.ScheduledAt,
		arg.CreatedAt,
	)
	return err
}

const update = `-- name: Update :exec
UPDATE targets
SET
    token = $1,
    employee_id = $2,
    campaign_id = $3,
    status = $4,
    scheduled_at = $5,
    created_at = $6
WHERE id = $7
`

type UpdateParams struct {
	Token       string
	EmployeeID  uuid.UUID
	CampaignID  uuid.UUID
	Status      string
	ScheduledAt pgtype.Timestamptz
	CreatedAt   pgtype.Timestamptz
	ID          uuid.UUID
}

func (q *Queries) Update(ctx context.Context, arg UpdateParams) error {
	_, err := q.db.Exec(ctx, update,
		arg.Token,
		arg.EmployeeID,
		arg.CampaignID,
		arg.Status,
		arg.ScheduledAt,
		arg.CreatedAt,
		arg.ID,
	)
	return err
}
